spring:
  #\u5173\u95ED\u7F13\u5B58
  thymeleaf:
    cache: false
  #\u6FC0\u6D3B\u6307\u5B9A\u7684\u73AF\u5883
  profiles:
    active: pro
  devtools:
    restart:
      enabled: true
comment.avatar: /images/avatar.jpg